### ISSUE TITLE
Huge RAM usage / memory leak

### ISSUE THREAD

**Issue by mdPlusPlus** [Coloradohusky/TikUp#25]
![tikup_RAM](https://user-images.githubusercontent.com/9272131/103407550-58e04080-4b5f-11eb-8a00-6b6e8bce372f.png)

KUbuntu 20.04.1 LTS  
tikup-2020.12.26

It runs until it fully depletes my 16GB RAM + 1GB Swap, then crashes. Happens after downloading ~30 videos.

Installed by issuing `pip3 install --pre -U --force-reinstall tikup` and `pip3 install testresources` (because I got the error "ERROR: launchpadlib 1.10.13 requires testresources, which is not installed.").

**Comment by Coloradohusky** [comment]
Huh, I'll have to investigate this further, I've been having this issue occasionally as well

**Comment by Coloradohusky** [comment]
My error looks something like this:

```
Traceback (most recent call last):
  File "c:\users\coloradohusky\appdata\local\programs\python\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\coloradohusky\appdata\local\programs\python\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\coloradohusky\AppData\Local\Programs\Python\Python38\Scripts\tikup.exe\__main__.py", line 7, in <module>
  File "c:\users\coloradohusky\appdata\local\programs\python\python38\lib\site-packages\tikup\tikup.py", line 245, in main
    tiktoks = downloadTikToks(username, tiktoks, file, downloadType, did)
  File "c:\users\coloradohusky\appdata\local\programs\python\python38\lib\site-packages\tikup\tikup.py", line 178, in downloadTikToks
    tiktokObj = getTikTokObject(tiktok, did)
  File "c:\users\coloradohusky\appdata\local\programs\python\python38\lib\site-packages\tikup\tikup.py", line 206, in getTikTokObject
    thing = api.getTikTokById(tiktokId, custom_did=did)
  File "c:\users\coloradohusky\appdata\local\programs\python\python38\lib\site-packages\TikTokApi\tiktok.py", line 1008, in getTikTokById
    return self.getData(url=api_url, **kwargs)
  File "c:\users\coloradohusky\appdata\local\programs\python\python38\lib\site-packages\TikTokApi\tiktok.py", line 159, in getData
    verify_fp, did, signature = self.browser.sign_url(**kwargs)
  File "c:\users\coloradohusky\appdata\local\programs\python\python38\lib\site-packages\TikTokApi\browser.py", line 164, in sign_url
    page = self.create_page()
  File "c:\users\coloradohusky\appdata\local\programs\python\python38\lib\site-packages\TikTokApi\browser.py", line 116, in create_page
    context = self.browser.newContext(**iphone)
  File "c:\users\coloradohusky\appdata\local\programs\python\python38\lib\site-packages\playwright\sync_api.py", line 6188, in newContext
    self._sync(
  File "c:\users\coloradohusky\appdata\local\programs\python\python38\lib\site-packages\playwright\sync_base.py", line 107, in _sync
    return future.result()
  File "c:\users\coloradohusky\appdata\local\programs\python\python38\lib\site-packages\playwright\browser.py", line 114, in newContext
    channel = await self._channel.send("newContext", params)
  File "c:\users\coloradohusky\appdata\local\programs\python\python38\lib\site-packages\playwright\connection.py", line 39, in send
    result = await callback.future
playwright.helper.Error: Protocol error (Playwright.createContext): Browser has been closed.
ERROR:asyncio:Exception in callback SyncBase._sync.<locals>.callback(<Task finishe...een closed.')>) at c:\users\coloradohusky\appdata\local\programs\python\python38\lib\site-packages\playwright\sync_base.py:100
handle: <Handle SyncBase._sync.<locals>.callback(<Task finishe...een closed.')>) at c:\users\coloradohusky\appdata\local\programs\python\python38\lib\site-packages\playwright\sync_base.py:100>
Traceback (most recent call last):
  File "c:\users\coloradohusky\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "c:\users\coloradohusky\appdata\local\programs\python\python38\lib\site-packages\playwright\sync_base.py", line 101, in callback
    g_self.switch()
greenlet.GreenletExit
```

Even though you're on Ubuntu, does the error message look similar?

Also, for now, just download/upload in small amounts with `--limit`, that seems to help for me

**Comment by mdPlusPlus** [comment]
Unfortunately I'm getting another error now:

    tikup --use-download-archive --no-delete tiktok
    
    [...]
    requests.exceptions.SSLError: HTTPSConnectionPool(host='tiktok.com', port=443): Max retries exceeded with url: /@tiktok?lang=en (Caused by SSLError(SSLCertVerificationError("hostname 'tiktok.com' doesn't match either of '*.snssdk.com', 'snssdk.com'")))

TikTokApi-3.8.9  
tikup-2020.12.26

I had SSL/TLS issues with youtube-dl before (for reasons I have yet to figure out) and was able to work around those by issuing `--no-check-certificate`. Is there such an option for tikup?

**Comment by marcus99661** [comment]
I think I have found out that the memory leak happens at the "getTikTokObject" function.
![image](https://user-images.githubusercontent.com/48325721/108132742-11385880-70bc-11eb-93df-bb9bbfe22047.png)
The RAM usage went up by 0.2% per cent every time it found a deleted or a new TikTok.
Hope this helps.

**Comment by Coloradohusky** [comment]
Does the recent TikTok-API update help at all? (https://github.com/davidteather/TikTok-Api/releases/tag/V3.9.0)

**Comment by marcus99661** [comment]
No, doesn't look like that fixed it.
You can test it out for yourself with this:
```python
from TikTokApi import TikTokApi
import psutil

api = TikTokApi()

while (True):
    api.getTikTokById("6929863113277705477", custom_did="86756746")
    print("RAM usage per cent: " + str(psutil.virtual_memory()[2]))
```

**Comment by marcus99661** [comment]
Also I sometimes get a playwright error which might help little bit: 
```
(node:45184) UnhandledPromiseRejectionWarning: Error: EPIPE: broken pipe, write
    at Socket._write (internal/net.js:54:25)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at Transport.send (C:\snapshot\playwright-cli\node_modules\playwright\lib\protocol\transport.js:43:25)
    at DispatcherConnection.onmessage (C:\snapshot\playwright-cli\lib\driver.js:49:61)
    at DispatcherConnection.sendMessageToClient (C:\snapshot\playwright-cli\node_modules\playwright\lib\dispatchers\dispatcher.js:129:14)
    at PageDispatcher._dispatchEvent (C:\snapshot\playwright-cli\node_modules\playwright\lib\dispatchers\dispatcher.js:70:26)
    at Page.<anonymous> (C:\snapshot\playwright-cli\node_modules\playwright\lib\dispatchers\pageDispatcher.js:42:18)
    at Page.emit (events.js:315:20)
(node:45184) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 227)
(node:45184) UnhandledPromiseRejectionWarning: Error: EPIPE: broken pipe, write
    at Socket._write (internal/net.js:54:25)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at Transport.send (C:\snapshot\playwright-cli\node_modules\playwright\lib\protocol\transport.js:43:25)
    at DispatcherConnection.onmessage (C:\snapshot\playwright-cli\lib\driver.js:49:61)
    at DispatcherConnection.sendMessageToClient (C:\snapshot\playwright-cli\node_modules\playwright\lib\dispatchers\dispatcher.js:129:14)
    at PageDispatcher._dispatchEvent (C:\snapshot\playwright-cli\node_modules\playwright\lib\dispatchers\dispatcher.js:70:26)
    at Page.<anonymous> (C:\snapshot\playwright-cli\node_modules\playwright\lib\dispatchers\pageDispatcher.js:42:18)
    at Page.emit (events.js:315:20)
(node:45184) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 228)
(node:45184) UnhandledPromiseRejectionWarning: Error: EPIPE: broken pipe, write
    at Socket._write (internal/net.js:54:25)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at Transport.send (C:\snapshot\playwright-cli\node_modules\playwright\lib\protocol\transport.js:43:25)
    at DispatcherConnection.onmessage (C:\snapshot\playwright-cli\lib\driver.js:49:61)
    at DispatcherConnection.sendMessageToClient (C:\snapshot\playwright-cli\node_modules\playwright\lib\dispatchers\dispatcher.js:129:14)
    at PageDispatcher._dispatchEvent (C:\snapshot\playwright-cli\node_modules\playwright\lib\dispatchers\dispatcher.js:70:26)
    at Page.<anonymous> (C:\snapshot\playwright-cli\node_modules\playwright\lib\dispatchers\pageDispatcher.js:42:18)
    at Page.emit (events.js:315:20)
(node:45184) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 229)
```
The "rejection id" is how many times it has done the api.getTikTokById function. The problem definitely seems to be with the playwright creating a new browser everytime, but I haven't played around with playwright so I don't know.

**Comment by Coloradohusky** [comment]
@mdPlusPlus, is the issue fixed for you too?

**Comment by mdPlusPlus** [comment]
`pip3 install --pre -U --force-reinstall tikup` results in `ERROR: selenium 4.0.0b1 has requirement urllib3[secure]==1.26.2, but you'll have urllib3 1.26.3 which is incompatible.` even in a clean Docker `ubuntu:latest` container. `pip3 install tikup && python3 -m playwright install` however installs fine. Just so you know.

Now to the topic of the actual issue (tested on host and in container):

    # tikup tiktok
    
    ERROR:root:TikTok response: 
    Traceback (most recent call last):
      File "/usr/local/bin/tikup", line 8, in <module>
        sys.exit(main())
      File "/usr/local/lib/python3.8/dist-packages/tikup/tikup.py", line 244, in main
        tiktoks = getUsernameVideos(username, limit)
      File "/usr/local/lib/python3.8/dist-packages/tikup/tikup.py", line 26, in getUsernameVideos
        tiktoks = api.byUsername(username, count=count)
      File "/usr/local/lib/python3.8/dist-packages/TikTokApi/tiktok.py", line 519, in byUsername
        return self.userPosts(
      File "/usr/local/lib/python3.8/dist-packages/TikTokApi/tiktok.py", line 481, in userPosts
        res = self.getData(url=api_url, **kwargs)
      File "/usr/local/lib/python3.8/dist-packages/TikTokApi/tiktok.py", line 211, in getData
        raise EmptyResponseError(
    TikTokApi.exceptions.EmptyResponseError: Empty response from Tiktok to https://m.tiktok.com/api/item_list/?aid=1988&app_name=tiktok_web&device_platform=web&referer=&root_referer=&user_agent=Mozilla%252F5.0%2B%28iPhone%253B%2BCPU%2BiPhone%2BOS%2B12_2%2Blike%2BMac%2BOS%2BX%29%2BAppleWebKit%252F605.1.15%2B%28KHTML%2C%2Blike%2BGecko%29%2BVersion%252F13.0%2BMobile%252F15E148%2BSafari%252F604.1&cookie_enabled=true&screen_width=1650&screen_height=979&browser_language=&browser_platform=&browser_name=&browser_version=&browser_online=true&ac=4g&timezone_name=&appId=1233&appType=m&isAndroid=False&isMobile=False&isIOS=False&OS=windows&count=35&id=107955&type=1&secUid=MS4wLjABAAAAv7iSuuXDJGDvJkmH_vz1qkDZYo1apxgzaxdBSeIuPiM&maxCursor=0&minCursor=0&sourceType=8&appId=1233&region=US&priority_region=US&language=en&verifyFp=verify_khr3jabg_V7ucdslq_Vrw9_4KPb_AJ1b_Ks706M8zIJTq&did=1632132202942595715&_signature=_02B4Z6wo00f01Vx5lWQAAIBDY9ELEN.JJVFcaJHAADcw66

I'm not quite sure what to make of this.

**Comment by mdPlusPlus** [comment]
Update: Works without issues now.

    TikTokApi           3.9.2               
    tikup               2021.3.13
    youtube-dl          2021.3.14
