### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by UnixCro** [Coloradohusky/TikUp#31]
```
pip3 install --user tikup

Collecting tikup
  Using cached https://files.pythonhosted.org/packages/32/22/2e0ba03d500dcfc24a365818bf211c35fb5990c1502708b2c68b952059b1/tikup-2021.3.13-py3-none-any.whl
Collecting TikTokApi>=3.9.2 (from tikup)
  Using cached https://files.pythonhosted.org/packages/2e/64/03946259224ed13a96d8f43652bb49328a17d5ba4e4c1ba40493aa6f169f/TikTokApi-3.9.9.1.tar.gz
Requirement already satisfied: youtube-dl>=2021.2.10 in /Library/Python/3.8/site-packages (from tikup) (2021.6.6)
Collecting internetarchive>=1.9.9 (from tikup)
  Using cached https://files.pythonhosted.org/packages/02/a1/b4fdf68ea8525402c21d28b685d9f14bc9bff39b129c65f2a845d89daf4b/internetarchive-2.0.3-py2.py3-none-any.whl
Collecting playwright>=1.9.2 (from tikup)
 
ERROR: Could not find a version that satisfies the requirement playwright>=1.9.2 (from tikup) (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.7.0, 0.7.1, 0.8.0, 0.140.0, 0.142.0, 0.142.1, 0.142.2, 0.142.3, 0.150.0, 0.151.0, 0.151.1, 0.152.0, 0.162.0, 0.162.1, 0.162.2)
ERROR: No matching distribution found for playwright>=1.9.2 (from tikup)

```

**Comment by Coloradohusky** [comment]
That's odd, as the latest version on Playwright on PyPI is 1.12.1 (https://pypi.org/project/playwright/1.12.1/#history) - can you post the output when run with -v?

**Comment by UnixCro** [comment]
Of course, but it  is very much.

[Gesicherte Terminal-Ausgabe.txt](https://github.com/Coloradohusky/TikUp/files/6803925/Gesicherte.Terminal-Ausgabe.txt)

**Comment by Coloradohusky** [comment]
Try updating pip, `pip install --upgrade pip`

**Comment by UnixCro** [comment]
Since there is unfortunately no "pip" and don't ask me why it says I should enter the command even though it doesn't work, there is only "pip3" under macOS 11

And it actually worked. I entered the following:
`pip3 install --upgrade --user pip`

When I tried to download something the next error message came up:

```
home@hostname ~ % python3 /Users/home/Library/Python/3.8/lib/python/site-packages/packages/tikup.py
usage: tikup.py [-h] [--no-delete] [--hashtag] [--limit LIMIT] [--use-download-archive] [--id] [--liked] user
tikup.py: error: the following arguments are required: user

```

<br>

```
home@hostname ~ % python3 /Users/home/Library/Python/3.8/lib/python/site-packages/packages/tikup.py videozeugs

Traceback (most recent call last):
  File "/Users/home/Library/Python/3.8/lib/python/site-packages/playwright/_impl/_browser_type.py", line 86, in launch
    return from_channel(await self._channel.send("launch", params))
  File "/Users/home/Library/Python/3.8/lib/python/site-packages/playwright/_impl/_connection.py", line 36, in send
    return await self.inner_send(method, params, False)
  File "/Users/home/Library/Python/3.8/lib/python/site-packages/playwright/_impl/_connection.py", line 54, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Failed to launch webkit because executable doesn't exist at /Users/home/Library/Caches/ms-playwright/webkit-1492/pw_run.sh
Try re-installing playwright with "npm install playwright"


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/home/Library/Python/3.8/lib/python/site-packages/packages/tikup.py", line 213, in <module>
    main()
  File "/Users/home/Library/Python/3.8/lib/python/site-packages/packages/tikup.py", line 202, in main
    tiktoks = getUsernameVideos(username, limit)
  File "/Users/home/Library/Python/3.8/lib/python/site-packages/packages/tikup.py", line 15, in getUsernameVideos
    api = TikTokApi()
  File "/Users/home/Library/Python/3.8/lib/python/site-packages/TikTokApi/tiktok.py", line 59, in __init__
    self.browser = browser(**kwargs)
  File "/Users/home/Library/Python/3.8/lib/python/site-packages/TikTokApi/browser.py", line 82, in __init__
    raise e
  File "/Users/home/Library/Python/3.8/lib/python/site-packages/TikTokApi/browser.py", line 78, in __init__
    self.browser = get_playwright().webkit.launch(
  File "/Users/home/Library/Python/3.8/lib/python/site-packages/playwright/sync_api/_generated.py", line 9430, in launch
    self._sync(
  File "/Users/shome/Library/Python/3.8/lib/python/site-packages/playwright/_impl/_sync_base.py", line 103, in _sync
    return task.result()
  File "/Users/home/Library/Python/3.8/lib/python/site-packages/playwright/_impl/_browser_type.py", line 89, in launch
    raise not_installed_error(f'"{self.name}" browser was not found.')
playwright._impl._api_types.Error: 
================================================================================
"webkit" browser was not found.
Please complete Playwright installation via running

    "python -m playwright install"

================================================================================
```

**Comment by Coloradohusky** [comment]
Can you try installing playwright again? Should be `pip3 install --user playwright`

**Comment by UnixCro** [comment]
Yes

```
home@hostname ~ % pip3 install --user playwrig

WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
ERROR: Could not find a version that satisfies the requirement playwrig (from versions: none)
ERROR: No matching distribution found for playwrig
```

**Comment by Coloradohusky** [comment]
Just updated - try the latest version

**Comment by UnixCro** [comment]
Hi, it still doesn't work. Here is the entire issue

```
pip3 install -U tikup

WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: tikup in ./Library/Python/3.8/lib/python/site-packages (2021.3.13)
Collecting tikup

Downloading tikup-2021.7.25-py3-none-any.whl (8.5 kB)
Requirement already satisfied: TikTokApi>=3.9.9 in ./Library/Python/3.8/lib/python/site-packages (from tikup) (3.9.9.1)
Requirement already satisfied: youtube-dl>=2021.6.6 in /Library/Python/3.8/site-packages (from tikup) (2021.6.6)
Requirement already satisfied: internetarchive>=2.0.3 in ./Library/Python/3.8/lib/python/site-packages (from tikup) (2.0.3)
Requirement already satisfied: playwright>=1.9.2 in ./Library/Python/3.8/lib/python/site-packages (from tikup) (1.12.1)
Requirement already satisfied: requests<3.0.0,>=2.9.1 in /Library/Python/3.8/site-packages (from internetarchive>=2.0.3->tikup) (2.25.1)
Requirement already satisfied: docopt<0.7.0,>=0.6.0 in ./Library/Python/3.8/lib/python/site-packages (from internetarchive>=2.0.3->tikup) (0.6.2)
Requirement already satisfied: schema>=0.4.0 in ./Library/Python/3.8/lib/python/site-packages (from internetarchive>=2.0.3->tikup) (0.7.4)
Requirement already satisfied: six<2.0.0,>=1.13.0 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages (from internetarchive>=2.0.3->tikup) (1.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /Library/Python/3.8/site-packages (from internetarchive>=2.0.3->tikup) (4.55.1)
Requirement already satisfied: jsonpatch>=0.4 in ./Library/Python/3.8/lib/python/site-packages (from internetarchive>=2.0.3->tikup) (1.32)
Requirement already satisfied: backports.csv<1.07 in ./Library/Python/3.8/lib/python/site-packages (from internetarchive>=2.0.3->tikup) (1.0.7)
Requirement already satisfied: jsonpointer>=1.9 in ./Library/Python/3.8/lib/python/site-packages (from jsonpatch>=0.4->internetarchive>=2.0.3->tikup) (2.1)
Requirement already satisfied: greenlet>=1.0.0 in ./Library/Python/3.8/lib/python/site-packages (from playwright>=1.9.2->tikup) (1.1.0)
Requirement already satisfied: typing-extensions in ./Library/Python/3.8/lib/python/site-packages (from playwright>=1.9.2->tikup) (3.10.0.0)
Requirement already satisfied: websockets>=8.1 in /Library/Python/3.8/site-packages (from playwright>=1.9.2->tikup) (8.1)

Collecting pyee>=8.0.1
  Using cached pyee-8.1.0-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Python/3.8/site-packages (from requests<3.0.0,>=2.9.1->internetarchive>=2.0.3->tikup) (2021.5.30)
Requirement already satisfied: idna<3,>=2.5 in /Library/Python/3.8/site-packages (from requests<3.0.0,>=2.9.1->internetarchive>=2.0.3->tikup) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in /Library/Python/3.8/site-packages (from requests<3.0.0,>=2.9.1->internetarchive>=2.0.3->tikup) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Python/3.8/site-packages (from requests<3.0.0,>=2.9.1->internetarchive>=2.0.3->tikup) (1.26.6)
Requirement already satisfied: contextlib2>=0.5.5 in ./Library/Python/3.8/lib/python/site-packages (from schema>=0.4.0->internetarchive>=2.0.3->tikup) (21.6.0)
Requirement already satisfied: selenium in ./Library/Python/3.8/lib/python/site-packages (from TikTokApi>=3.9.9->tikup) (3.141.0)
Requirement already satisfied: selenium-stealth in ./Library/Python/3.8/lib/python/site-packages (from TikTokApi>=3.9.9->tikup) (1.0.6)
Installing collected packages: pyee, tikup
  Attempting uninstall: tikup
    Found existing installation: tikup 2021.3.13
    Uninstalling tikup-2021.3.13:
      Successfully uninstalled tikup-2021.3.13

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyppeteer 0.2.3 requires pyee<8.0.0,>=7.0.1, but you have pyee 8.1.0 which is incompatible.
Successfully installed pyee-8.1.0 tikup-2021.7.2
```

And then I tried again

```
home@hostname ~ % python3 ~/Library/Python/3.8/lib/python/site-packages/packages/tikup.py 

usage: tikup.py [-h] [--no-delete] [--hashtag] [--limit LIMIT] [--use-download-archive] [--id] [--liked] user
tikup.py: error: the following arguments are required: user

home@hostname ~ % python3 ~/Library/Python/3.8/lib/python/site-packages/packages/tikup.py  videozeugs

Traceback (most recent call last):
  File "/Users/home/Library/Python/3.8/lib/python/site-packages/playwright/_impl/_browser_type.py", line 86, in launch
    return from_channel(await self._channel.send("launch", params))
  File "/Users/home/Library/Python/3.8/lib/python/site-packages/playwright/_impl/_connection.py", line 36, in send
    return await self.inner_send(method, params, False)
  File "/Users/home/Library/Python/3.8/lib/python/site-packages/playwright/_impl/_connection.py", line 54, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Failed to launch webkit because executable doesn't exist at /Users/home/Library/Caches/ms-playwright/webkit-1492/pw_run.sh
Try re-installing playwright with "npm install playwright"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/home/Library/Python/3.8/lib/python/site-packages/packages/tikup.py", line 213, in <module>
    main()
  File "/Users/home/Library/Python/3.8/lib/python/site-packages/packages/tikup.py", line 202, in main
    tiktoks = getUsernameVideos(username, limit)
  File "/Users/shome/Library/Python/3.8/lib/python/site-packages/packages/tikup.py", line 15, in getUsernameVideos
    api = TikTokApi()
  File "/Users/home/Library/Python/3.8/lib/python/site-packages/TikTokApi/tiktok.py", line 59, in __init__
    self.browser = browser(**kwargs)
  File "/Users/shome/Library/Python/3.8/lib/python/site-packages/TikTokApi/browser.py", line 82, in __init__
    raise e
  File "/Users/home/Library/Python/3.8/lib/python/site-packages/TikTokApi/browser.py", line 78, in __init__
    self.browser = get_playwright().webkit.launch(
  File "/Users/home/Library/Python/3.8/lib/python/site-packages/playwright/sync_api/_generated.py", line 9430, in launch
    self._sync(
  File "/Users/home/Library/Python/3.8/lib/python/site-packages/playwright/_impl/_sync_base.py", line 103, in _sync
    return task.result()
  File "/Users/home/Library/Python/3.8/lib/python/site-packages/playwright/_impl/_browser_type.py", line 89, in launch
    raise not_installed_error(f'"{self.name}" browser was not found.')
playwright._impl._api_types.Error: 
================================================================================
"webkit" browser was not found.
Please complete Playwright installation via running

    "python -m playwright install"

================================================================================




```

There is another tiktup.py in '~/Library/Python/3.8/lib/python/site-packages/tikup/tikup.py' I don´t know why its there and why is the other here '~/Library/Python/3.8/lib/python/site-packages/packages/tikup.py`

```
python3 ~/Library/Python/3.8/lib/python/site-packages/tikup/tikup.py

Traceback (most recent call last):
  File "/Users/home/Library/Python/3.8/lib/python/site-packages/tikup/tikup.py", line 12, in <module>
    from .argparser import parse_args
ImportError: attempted relative import with no known parent package
```

<h2>Reinstall</h2>

**Deinstall**

```
home@hostname ~ % pip3 uninstall  tikup             
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Found existing installation: tikup 2021.7.25
Uninstalling tikup-2021.7.25:
  Would remove:
    /Users/home/Library/Python/3.8/bin/tikup
    /Users/home/Library/Python/3.8/lib/python/site-packages/packages/*
    /Users/home/Library/Python/3.8/lib/python/site-packages/tikup-2021.7.25.dist-info/*
    /Users/home/Library/Python/3.8/lib/python/site-packages/tikup/*
Proceed (Y/n)? 
```
**Install**

```
home@hostname ~ % pip3 install --pre  tikup
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
Collecting tikup
  Using cached tikup-2021.7.25-py3-none-any.whl (8.5 kB)
Requirement already satisfied: internetarchive>=2.0.3 in ./Library/Python/3.8/lib/python/site-packages (from tikup) (2.0.3)
Requirement already satisfied: youtube-dl>=2021.6.6 in /Library/Python/3.8/site-packages (from tikup) (2021.6.6)
Requirement already satisfied: playwright>=1.9.2 in ./Library/Python/3.8/lib/python/site-packages (from tikup) (1.12.1)
Requirement already satisfied: TikTokApi>=3.9.9 in ./Library/Python/3.8/lib/python/site-packages (from tikup) (3.9.9.1)
Requirement already satisfied: backports.csv<1.07 in ./Library/Python/3.8/lib/python/site-packages (from internetarchive>=2.0.3->tikup) (1.0.7)
Requirement already satisfied: six<2.0.0,>=1.13.0 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages (from internetarchive>=2.0.3->tikup) (1.15.0)
Requirement already satisfied: docopt<0.7.0,>=0.6.0 in ./Library/Python/3.8/lib/python/site-packages (from internetarchive>=2.0.3->tikup) (0.6.2)
Requirement already satisfied: tqdm>=4.0.0 in /Library/Python/3.8/site-packages (from internetarchive>=2.0.3->tikup) (4.55.1)
Requirement already satisfied: schema>=0.4.0 in ./Library/Python/3.8/lib/python/site-packages (from internetarchive>=2.0.3->tikup) (0.7.4)
Requirement already satisfied: requests<3.0.0,>=2.9.1 in /Library/Python/3.8/site-packages (from internetarchive>=2.0.3->tikup) (2.25.1)
Requirement already satisfied: jsonpatch>=0.4 in ./Library/Python/3.8/lib/python/site-packages (from internetarchive>=2.0.3->tikup) (1.32)
Requirement already satisfied: jsonpointer>=1.9 in ./Library/Python/3.8/lib/python/site-packages (from jsonpatch>=0.4->internetarchive>=2.0.3->tikup) (2.1)
Requirement already satisfied: typing-extensions in ./Library/Python/3.8/lib/python/site-packages (from playwright>=1.9.2->tikup) (3.10.0.0)
Requirement already satisfied: pyee>=8.0.1 in ./Library/Python/3.8/lib/python/site-packages (from playwright>=1.9.2->tikup) (8.1.0)
Requirement already satisfied: greenlet>=1.0.0 in ./Library/Python/3.8/lib/python/site-packages (from playwright>=1.9.2->tikup) (1.1.0)
Requirement already satisfied: websockets>=8.1 in /Library/Python/3.8/site-packages (from playwright>=1.9.2->tikup) (8.1)
Requirement already satisfied: chardet<5,>=3.0.2 in /Library/Python/3.8/site-packages (from requests<3.0.0,>=2.9.1->internetarchive>=2.0.3->tikup) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /Library/Python/3.8/site-packages (from requests<3.0.0,>=2.9.1->internetarchive>=2.0.3->tikup) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Python/3.8/site-packages (from requests<3.0.0,>=2.9.1->internetarchive>=2.0.3->tikup) (1.26.6)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Python/3.8/site-packages (from requests<3.0.0,>=2.9.1->internetarchive>=2.0.3->tikup) (2021.5.30)
Requirement already satisfied: contextlib2>=0.5.5 in ./Library/Python/3.8/lib/python/site-packages (from schema>=0.4.0->internetarchive>=2.0.3->tikup) (21.6.0)
Requirement already satisfied: selenium-stealth in ./Library/Python/3.8/lib/python/site-packages (from TikTokApi>=3.9.9->tikup) (1.0.6)
Requirement already satisfied: selenium in ./Library/Python/3.8/lib/python/site-packages (from TikTokApi>=3.9.9->tikup) (3.141.0)
Installing collected packages: tikup
  WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /Users/home/Library/Python/3.8/include/python3.8/tikup
  sysconfig: /Users/home/Library/Python/3.8/include/tikup
  WARNING: Additional context:
  user = True
  home = None
  root = None
  prefix = None
  WARNING: The script tikup is installed in '/Users/home/Library/Python/3.8/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /Users/home/Library/Python/3.8/include/python3.8/UNKNOWN
sysconfig: /Users/home/Library/Python/3.8/include/UNKNOWN
Successfully installed tikup-2021.7.25
```

**Comment by Coloradohusky** [comment]
Running `python3 ~/Library/Python/3.8/lib/python/site-packages/tikup/tikup.py` will make it not work, try running just `tikup` instead

**Comment by UnixCro** [comment]
Unfortunately the output is the one of the same, which I have already postet.

I would not like post it because by to long text in makes more confusing.

I have again reinstalled tikup but with administrator privileges.

When I write only "tikup" in the Terminal immediately this again comes a little bit at the top by "Here"
