### ISSUE TITLE
AttributeError: 'TikTokApi' object has no attribute 'byUsername'

### ISSUE THREAD

**Issue by omerher** [Coloradohusky/TikUp#34]
When running the app, I get this error no matter what options I run with. 
```
Traceback (most recent call last):
  File "c:\users\hersh\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\hersh\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\hersh\AppData\Local\Programs\Python\Python39\Scripts\tikup.exe\__main__.py", line 7, in <module>
  File "c:\users\hersh\appdata\local\programs\python\python39\lib\site-packages\tikup\tikup.py", line 255, in main
    tiktoks = getUsernameVideos(username, limit)
  File "c:\users\hersh\appdata\local\programs\python\python39\lib\site-packages\tikup\tikup.py", line 27, in getUsernameVideos
    tiktoks = api.byUsername(username, count=count)
AttributeError: 'TikTokApi' object has no attribute 'byUsername'
```

Running on Windows
Python v3.9.6
pip v21.1.3

**Comment by gabefair** [comment]
I was coming here to say the same thing. I also got this error on MacOS and using tikup inside a Conda Environment.


```
% tikup dr.noc --use-download-archive
Traceback (most recent call last):
  File "/Users/username/opt/anaconda3/bin/tikup", line 8, in <module>
    sys.exit(main())
  File "/Users/username/opt/anaconda3/lib/python3.8/site-packages/tikup/tikup.py", line 255, in main
    tiktoks = getUsernameVideos(username, limit)
  File "/Users/username/opt/anaconda3/lib/python3.8/site-packages/tikup/tikup.py", line 27, in getUsernameVideos
    tiktoks = api.byUsername(username, count=count)
AttributeError: 'TikTokApi' object has no attribute 'byUsername'
```

**Comment by gabefair** [comment]
The tiktokApi has deprecated `byUsername`. I think it is now just `by_username ` as described here in the [docs](https://dteather.com/TikTok-Api/docs/TikTokApi/tiktok.html). Let me see if I can submit a PR to fix this

**Comment by gabefair** [comment]
I have now submitted a PR to fix this issue #35
